/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizmid;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Quinquee
 */
public class transaksi_pengembalian_buku extends javax.swing.JFrame {
    


    /**
     * Creates new form transaksi_pengembalian_buku
     */
    public transaksi_pengembalian_buku() {
        initComponents();
        kosongkan_data();
        koneksi_database();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        o_kembalian = new javax.swing.JTextField();
        o_telat = new javax.swing.JTextField();
        cmb_kode = new javax.swing.JComboBox<>();
        i_nama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        i_nobp = new javax.swing.JTextField();
        i_pinjam = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        o_buku = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        o_denda = new javax.swing.JTextField();
        i_bayar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setText("FORM TRANSAKSI PENGEMBALIAN BUKU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Denda");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Transaksi Pengembalian Buku ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Keterlambatan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Nama Mahasiswa");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Kode Buku");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        o_kembalian.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        o_kembalian.setText("O_kembalian");
        jPanel1.add(o_kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 120, -1));

        o_telat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        o_telat.setText("O_telat");
        o_telat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_telatActionPerformed(evt);
            }
        });
        jPanel1.add(o_telat, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 80, -1));

        cmb_kode.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmb_kode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Input Kode Buku-", "B001", "B002", "B003" }));
        cmb_kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_kodeActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        i_nama.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        i_nama.setText("I_nama");
        jPanel1.add(i_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 190, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("No BP");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Hari");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 70, 40));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Count");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 70, 40));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 70, 40));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 70, 40));

        i_nobp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        i_nobp.setText("I_noBP");
        i_nobp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_nobpActionPerformed(evt);
            }
        });
        jPanel1.add(i_nobp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 150, -1));

        i_pinjam.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        i_pinjam.setText("I_pinjam");
        jPanel1.add(i_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 80, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Lama Pinjam");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Hari");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Kembalian       Rp.");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        o_buku.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        o_buku.setText("O_buku");
        o_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_bukuActionPerformed(evt);
            }
        });
        jPanel1.add(o_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 190, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Nama Buku");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Jumlah Bayar  Rp.");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        o_denda.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        o_denda.setText("O_denda");
        jPanel1.add(o_denda, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 120, -1));

        i_bayar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        i_bayar.setText("I_bayar");
        i_bayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i_bayarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                i_bayarMouseExited(evt);
            }
        });
        i_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                i_bayarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                i_bayarKeyReleased(evt);
            }
        });
        jPanel1.add(i_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void i_nobpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_nobpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_nobpActionPerformed

    private void o_telatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_telatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_o_telatActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int denda = 0;
        denda = Integer.parseInt(o_telat.getText())*1000;
        o_denda.setText(String.valueOf(denda));
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        kosongkan_data();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void o_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_bukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_o_bukuActionPerformed

    private void cmb_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_kodeActionPerformed
        String nama_buku=null;
        if(cmb_kode.getSelectedItem()=="-Input Kode Buku-"){
            kosongkan_data();
        }
        else if(cmb_kode.getSelectedItem()=="B001"){
            nama_buku="Fisika";
        }
        else if(cmb_kode.getSelectedItem()=="B002"){
            nama_buku="Java & MySQL";
        }
        else if(cmb_kode.getSelectedItem()=="B003"){
            nama_buku="Bahasa Inggris";
        }
        
     o_buku.setText(nama_buku);   
    }//GEN-LAST:event_cmb_kodeActionPerformed

    private void i_bayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_i_bayarKeyPressed
        
    }//GEN-LAST:event_i_bayarKeyPressed

    private void i_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_i_bayarKeyReleased
        
    }//GEN-LAST:event_i_bayarKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            sql = "INSERT INTO pengembalian VALUES ('"+i_nobp.getText()+
                    "','"+i_nama.getText()+
                    "','"+cmb_kode.getSelectedItem()+
                    "','"+o_buku.getText()+
                    "','"+i_pinjam.getText()+
                    "','"+o_telat.getText()+
                    "','"+o_denda.getText()+
                    "')";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Tersimpan.....");
            kosongkan_data();
            stat.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal....." + e);
        }
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void i_bayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i_bayarMouseClicked
        
    }//GEN-LAST:event_i_bayarMouseClicked

    private void i_bayarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i_bayarMouseExited
    int kembalian;
      
        kembalian = Integer.parseInt(i_bayar.getText())-Integer.parseInt(o_denda.getText());
        
        o_kembalian.setText(String.valueOf(kembalian));
    }//GEN-LAST:event_i_bayarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi_pengembalian_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi_pengembalian_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi_pengembalian_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi_pengembalian_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi_pengembalian_buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_kode;
    private javax.swing.JTextField i_bayar;
    private javax.swing.JTextField i_nama;
    private javax.swing.JTextField i_nobp;
    private javax.swing.JTextField i_pinjam;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField o_buku;
    private javax.swing.JTextField o_denda;
    private javax.swing.JTextField o_kembalian;
    private javax.swing.JTextField o_telat;
    // End of variables declaration//GEN-END:variables

private void kosongkan_data(){
    i_nobp.setText("");
    i_nama.setText("");
    cmb_kode.setSelectedIndex(0);
    o_buku.setText("");
    i_pinjam.setText("");
    o_telat.setText("");
    o_denda.setText("");
    i_bayar.setText("");
    o_kembalian.setText("");
    i_nobp.requestFocus();
} 

private Connection con;
private Statement stat;
private ResultSet rs;
private String sql;

private void koneksi_database(){
   try {
       Class.forName("com.mysql.jdbc.Driver");
       System.out.println("Driver Ditemukan...");
       try {
           String url = "jdbc:mysql://localhost:3306/pengembalian_buku?user=root&password=";
           con = DriverManager.getConnection(url);
           System.out.println("Terkoneksi.....");
           
       } catch (SQLException e){
           System.err.println("Tidak Terkoneksi.....");
       }
   } catch (ClassNotFoundException e){
       System.err.println("Driver Tidak Ditemukan.......");
   }
}
    
}
